# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from serial_comm/RobotControl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RobotControl(genpy.Message):
  _md5sum = "c444a667b2720c4168deb47dd4f537a3"
  _type = "serial_comm/RobotControl"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 motor1_speed
int16 motor2_speed
int16 motor3_speed
int16 motor4_speed
int16 joint1_angle
int16 joint2_angle
int16 joint3_angle
int16 wrist_angle
int16 gripper_angle
uint8 rest_flag"""
  __slots__ = ['motor1_speed','motor2_speed','motor3_speed','motor4_speed','joint1_angle','joint2_angle','joint3_angle','wrist_angle','gripper_angle','rest_flag']
  _slot_types = ['int16','int16','int16','int16','int16','int16','int16','int16','int16','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motor1_speed,motor2_speed,motor3_speed,motor4_speed,joint1_angle,joint2_angle,joint3_angle,wrist_angle,gripper_angle,rest_flag

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotControl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.motor1_speed is None:
        self.motor1_speed = 0
      if self.motor2_speed is None:
        self.motor2_speed = 0
      if self.motor3_speed is None:
        self.motor3_speed = 0
      if self.motor4_speed is None:
        self.motor4_speed = 0
      if self.joint1_angle is None:
        self.joint1_angle = 0
      if self.joint2_angle is None:
        self.joint2_angle = 0
      if self.joint3_angle is None:
        self.joint3_angle = 0
      if self.wrist_angle is None:
        self.wrist_angle = 0
      if self.gripper_angle is None:
        self.gripper_angle = 0
      if self.rest_flag is None:
        self.rest_flag = 0
    else:
      self.motor1_speed = 0
      self.motor2_speed = 0
      self.motor3_speed = 0
      self.motor4_speed = 0
      self.joint1_angle = 0
      self.joint2_angle = 0
      self.joint3_angle = 0
      self.wrist_angle = 0
      self.gripper_angle = 0
      self.rest_flag = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9hB().pack(_x.motor1_speed, _x.motor2_speed, _x.motor3_speed, _x.motor4_speed, _x.joint1_angle, _x.joint2_angle, _x.joint3_angle, _x.wrist_angle, _x.gripper_angle, _x.rest_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 19
      (_x.motor1_speed, _x.motor2_speed, _x.motor3_speed, _x.motor4_speed, _x.joint1_angle, _x.joint2_angle, _x.joint3_angle, _x.wrist_angle, _x.gripper_angle, _x.rest_flag,) = _get_struct_9hB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9hB().pack(_x.motor1_speed, _x.motor2_speed, _x.motor3_speed, _x.motor4_speed, _x.joint1_angle, _x.joint2_angle, _x.joint3_angle, _x.wrist_angle, _x.gripper_angle, _x.rest_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 19
      (_x.motor1_speed, _x.motor2_speed, _x.motor3_speed, _x.motor4_speed, _x.joint1_angle, _x.joint2_angle, _x.joint3_angle, _x.wrist_angle, _x.gripper_angle, _x.rest_flag,) = _get_struct_9hB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9hB = None
def _get_struct_9hB():
    global _struct_9hB
    if _struct_9hB is None:
        _struct_9hB = struct.Struct("<9hB")
    return _struct_9hB
