// Generated by gencpp from file xrobot_msgs/ParamConfig.msg
// DO NOT EDIT!


#ifndef XROBOT_MSGS_MESSAGE_PARAMCONFIG_H
#define XROBOT_MSGS_MESSAGE_PARAMCONFIG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xrobot_msgs
{
template <class ContainerAllocator>
struct ParamConfig_
{
  typedef ParamConfig_<ContainerAllocator> Type;

  ParamConfig_()
    : chassis_type(0)
    , x_speed_scale(0.0)
    , y_speed_scale(0.0)
    , w_speed_scale(0.0)  {
    }
  ParamConfig_(const ContainerAllocator& _alloc)
    : chassis_type(0)
    , x_speed_scale(0.0)
    , y_speed_scale(0.0)
    , w_speed_scale(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _chassis_type_type;
  _chassis_type_type chassis_type;

   typedef float _x_speed_scale_type;
  _x_speed_scale_type x_speed_scale;

   typedef float _y_speed_scale_type;
  _y_speed_scale_type y_speed_scale;

   typedef float _w_speed_scale_type;
  _w_speed_scale_type w_speed_scale;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(DIFFERENTIAL_DRIVE)
  #undef DIFFERENTIAL_DRIVE
#endif
#if defined(_WIN32) && defined(ACKERMANN)
  #undef ACKERMANN
#endif
#if defined(_WIN32) && defined(MECANUM)
  #undef MECANUM
#endif

  enum {
    DIFFERENTIAL_DRIVE = 0u,
    ACKERMANN = 1u,
    MECANUM = 2u,
  };


  typedef boost::shared_ptr< ::xrobot_msgs::ParamConfig_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xrobot_msgs::ParamConfig_<ContainerAllocator> const> ConstPtr;

}; // struct ParamConfig_

typedef ::xrobot_msgs::ParamConfig_<std::allocator<void> > ParamConfig;

typedef boost::shared_ptr< ::xrobot_msgs::ParamConfig > ParamConfigPtr;
typedef boost::shared_ptr< ::xrobot_msgs::ParamConfig const> ParamConfigConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xrobot_msgs::ParamConfig_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xrobot_msgs::ParamConfig_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xrobot_msgs::ParamConfig_<ContainerAllocator1> & lhs, const ::xrobot_msgs::ParamConfig_<ContainerAllocator2> & rhs)
{
  return lhs.chassis_type == rhs.chassis_type &&
    lhs.x_speed_scale == rhs.x_speed_scale &&
    lhs.y_speed_scale == rhs.y_speed_scale &&
    lhs.w_speed_scale == rhs.w_speed_scale;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xrobot_msgs::ParamConfig_<ContainerAllocator1> & lhs, const ::xrobot_msgs::ParamConfig_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xrobot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xrobot_msgs::ParamConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xrobot_msgs::ParamConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xrobot_msgs::ParamConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xrobot_msgs::ParamConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xrobot_msgs::ParamConfig_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xrobot_msgs::ParamConfig_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xrobot_msgs::ParamConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f701675f55a47d8728e25b639a888073";
  }

  static const char* value(const ::xrobot_msgs::ParamConfig_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf701675f55a47d87ULL;
  static const uint64_t static_value2 = 0x28e25b639a888073ULL;
};

template<class ContainerAllocator>
struct DataType< ::xrobot_msgs::ParamConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xrobot_msgs/ParamConfig";
  }

  static const char* value(const ::xrobot_msgs::ParamConfig_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xrobot_msgs::ParamConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "########################################\n"
"# CONSTANTS\n"
"########################################\n"
"# Chassis Type\n"
"uint8 DIFFERENTIAL_DRIVE  = 0\n"
"uint8 ACKERMANN  = 1\n"
"uint8 MECANUM  = 2\n"
"\n"
"# Arm Type\n"
"\n"
"########################################\n"
"# Messages\n"
"########################################\n"
"uint8 chassis_type      # 底盘类型\n"
"float32 x_speed_scale     # 遥控的速度比例\n"
"float32 y_speed_scale \n"
"float32 w_speed_scale\n"
;
  }

  static const char* value(const ::xrobot_msgs::ParamConfig_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xrobot_msgs::ParamConfig_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.chassis_type);
      stream.next(m.x_speed_scale);
      stream.next(m.y_speed_scale);
      stream.next(m.w_speed_scale);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParamConfig_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xrobot_msgs::ParamConfig_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xrobot_msgs::ParamConfig_<ContainerAllocator>& v)
  {
    s << indent << "chassis_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.chassis_type);
    s << indent << "x_speed_scale: ";
    Printer<float>::stream(s, indent + "  ", v.x_speed_scale);
    s << indent << "y_speed_scale: ";
    Printer<float>::stream(s, indent + "  ", v.y_speed_scale);
    s << indent << "w_speed_scale: ";
    Printer<float>::stream(s, indent + "  ", v.w_speed_scale);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XROBOT_MSGS_MESSAGE_PARAMCONFIG_H
