// Generated by gencpp from file xrobot_msgs/SensorState.msg
// DO NOT EDIT!


#ifndef XROBOT_MSGS_MESSAGE_SENSORSTATE_H
#define XROBOT_MSGS_MESSAGE_SENSORSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace xrobot_msgs
{
template <class ContainerAllocator>
struct SensorState_
{
  typedef SensorState_<ContainerAllocator> Type;

  SensorState_()
    : header()
    , sonar()
    , illumination()
    , motor_encoder()
    , button()
    , battery(0.0)  {
      sonar.assign(0.0);

      illumination.assign(0);

      motor_encoder.assign(0);

      button.assign(0);
  }
  SensorState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sonar()
    , illumination()
    , motor_encoder()
    , button()
    , battery(0.0)  {
  (void)_alloc;
      sonar.assign(0.0);

      illumination.assign(0);

      motor_encoder.assign(0);

      button.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 4>  _sonar_type;
  _sonar_type sonar;

   typedef boost::array<uint8_t, 4>  _illumination_type;
  _illumination_type illumination;

   typedef boost::array<int32_t, 4>  _motor_encoder_type;
  _motor_encoder_type motor_encoder;

   typedef boost::array<uint8_t, 7>  _button_type;
  _button_type button;

   typedef float _battery_type;
  _battery_type battery;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(LEFT_FRONT_MOTOR)
  #undef LEFT_FRONT_MOTOR
#endif
#if defined(_WIN32) && defined(RIGHT_FRONT_MOTOR)
  #undef RIGHT_FRONT_MOTOR
#endif
#if defined(_WIN32) && defined(LEFT_BACK_MOTOR)
  #undef LEFT_BACK_MOTOR
#endif
#if defined(_WIN32) && defined(RIGHT_BACK_MOTOR)
  #undef RIGHT_BACK_MOTOR
#endif
#if defined(_WIN32) && defined(FRONT_SENSOR)
  #undef FRONT_SENSOR
#endif
#if defined(_WIN32) && defined(RIGHT_SENSOR)
  #undef RIGHT_SENSOR
#endif
#if defined(_WIN32) && defined(BACK_SENSOR)
  #undef BACK_SENSOR
#endif
#if defined(_WIN32) && defined(LEFT_SENSOR)
  #undef LEFT_SENSOR
#endif

  enum {
    LEFT_FRONT_MOTOR = 0u,
    RIGHT_FRONT_MOTOR = 1u,
    LEFT_BACK_MOTOR = 2u,
    RIGHT_BACK_MOTOR = 3u,
    FRONT_SENSOR = 0u,
    RIGHT_SENSOR = 1u,
    BACK_SENSOR = 2u,
    LEFT_SENSOR = 3u,
  };


  typedef boost::shared_ptr< ::xrobot_msgs::SensorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xrobot_msgs::SensorState_<ContainerAllocator> const> ConstPtr;

}; // struct SensorState_

typedef ::xrobot_msgs::SensorState_<std::allocator<void> > SensorState;

typedef boost::shared_ptr< ::xrobot_msgs::SensorState > SensorStatePtr;
typedef boost::shared_ptr< ::xrobot_msgs::SensorState const> SensorStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xrobot_msgs::SensorState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xrobot_msgs::SensorState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xrobot_msgs::SensorState_<ContainerAllocator1> & lhs, const ::xrobot_msgs::SensorState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sonar == rhs.sonar &&
    lhs.illumination == rhs.illumination &&
    lhs.motor_encoder == rhs.motor_encoder &&
    lhs.button == rhs.button &&
    lhs.battery == rhs.battery;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xrobot_msgs::SensorState_<ContainerAllocator1> & lhs, const ::xrobot_msgs::SensorState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xrobot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xrobot_msgs::SensorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xrobot_msgs::SensorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xrobot_msgs::SensorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xrobot_msgs::SensorState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xrobot_msgs::SensorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xrobot_msgs::SensorState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xrobot_msgs::SensorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "229634ca6575e167dd4ffa0fff8b30f5";
  }

  static const char* value(const ::xrobot_msgs::SensorState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x229634ca6575e167ULL;
  static const uint64_t static_value2 = 0xdd4ffa0fff8b30f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::xrobot_msgs::SensorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xrobot_msgs/SensorState";
  }

  static const char* value(const ::xrobot_msgs::SensorState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xrobot_msgs::SensorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "########################################\n"
"# CONSTANTS\n"
"########################################\n"
"# Motor\n"
"uint8 LEFT_FRONT_MOTOR  = 0\n"
"uint8 RIGHT_FRONT_MOTOR = 1\n"
"uint8 LEFT_BACK_MOTOR  = 2\n"
"uint8 RIGHT_BACK_MOTOR = 3\n"
"\n"
"# Sensor\n"
"uint8 FRONT_SENSOR  = 0\n"
"uint8 RIGHT_SENSOR = 1\n"
"uint8 BACK_SENSOR  = 2\n"
"uint8 LEFT_SENSOR = 3\n"
"\n"
"########################################\n"
"# Messages\n"
"########################################\n"
"Header  header\n"
"float32[4] sonar\n"
"uint8[4] illumination\n"
"int32[4] motor_encoder\n"
"uint8[7] button\n"
"float32  battery\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::xrobot_msgs::SensorState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xrobot_msgs::SensorState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sonar);
      stream.next(m.illumination);
      stream.next(m.motor_encoder);
      stream.next(m.button);
      stream.next(m.battery);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xrobot_msgs::SensorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xrobot_msgs::SensorState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sonar[]" << std::endl;
    for (size_t i = 0; i < v.sonar.size(); ++i)
    {
      s << indent << "  sonar[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.sonar[i]);
    }
    s << indent << "illumination[]" << std::endl;
    for (size_t i = 0; i < v.illumination.size(); ++i)
    {
      s << indent << "  illumination[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.illumination[i]);
    }
    s << indent << "motor_encoder[]" << std::endl;
    for (size_t i = 0; i < v.motor_encoder.size(); ++i)
    {
      s << indent << "  motor_encoder[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.motor_encoder[i]);
    }
    s << indent << "button[]" << std::endl;
    for (size_t i = 0; i < v.button.size(); ++i)
    {
      s << indent << "  button[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.button[i]);
    }
    s << indent << "battery: ";
    Printer<float>::stream(s, indent + "  ", v.battery);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XROBOT_MSGS_MESSAGE_SENSORSTATE_H
