// Generated by gencpp from file ros_jetson_stats/jetson_clocks.msg
// DO NOT EDIT!


#ifndef ROS_JETSON_STATS_MESSAGE_JETSON_CLOCKS_H
#define ROS_JETSON_STATS_MESSAGE_JETSON_CLOCKS_H

#include <ros/service_traits.h>


#include <ros_jetson_stats/jetson_clocksRequest.h>
#include <ros_jetson_stats/jetson_clocksResponse.h>


namespace ros_jetson_stats
{

struct jetson_clocks
{

typedef jetson_clocksRequest Request;
typedef jetson_clocksResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct jetson_clocks
} // namespace ros_jetson_stats


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_jetson_stats::jetson_clocks > {
  static const char* value()
  {
    return "8c3d867c150b13d0a3fcbf4f14955089";
  }

  static const char* value(const ::ros_jetson_stats::jetson_clocks&) { return value(); }
};

template<>
struct DataType< ::ros_jetson_stats::jetson_clocks > {
  static const char* value()
  {
    return "ros_jetson_stats/jetson_clocks";
  }

  static const char* value(const ::ros_jetson_stats::jetson_clocks&) { return value(); }
};


// service_traits::MD5Sum< ::ros_jetson_stats::jetson_clocksRequest> should match
// service_traits::MD5Sum< ::ros_jetson_stats::jetson_clocks >
template<>
struct MD5Sum< ::ros_jetson_stats::jetson_clocksRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_jetson_stats::jetson_clocks >::value();
  }
  static const char* value(const ::ros_jetson_stats::jetson_clocksRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_jetson_stats::jetson_clocksRequest> should match
// service_traits::DataType< ::ros_jetson_stats::jetson_clocks >
template<>
struct DataType< ::ros_jetson_stats::jetson_clocksRequest>
{
  static const char* value()
  {
    return DataType< ::ros_jetson_stats::jetson_clocks >::value();
  }
  static const char* value(const ::ros_jetson_stats::jetson_clocksRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_jetson_stats::jetson_clocksResponse> should match
// service_traits::MD5Sum< ::ros_jetson_stats::jetson_clocks >
template<>
struct MD5Sum< ::ros_jetson_stats::jetson_clocksResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_jetson_stats::jetson_clocks >::value();
  }
  static const char* value(const ::ros_jetson_stats::jetson_clocksResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_jetson_stats::jetson_clocksResponse> should match
// service_traits::DataType< ::ros_jetson_stats::jetson_clocks >
template<>
struct DataType< ::ros_jetson_stats::jetson_clocksResponse>
{
  static const char* value()
  {
    return DataType< ::ros_jetson_stats::jetson_clocks >::value();
  }
  static const char* value(const ::ros_jetson_stats::jetson_clocksResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_JETSON_STATS_MESSAGE_JETSON_CLOCKS_H
