// Generated by gencpp from file ros_jetson_stats/nvpmodelRequest.msg
// DO NOT EDIT!


#ifndef ROS_JETSON_STATS_MESSAGE_NVPMODELREQUEST_H
#define ROS_JETSON_STATS_MESSAGE_NVPMODELREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_jetson_stats
{
template <class ContainerAllocator>
struct nvpmodelRequest_
{
  typedef nvpmodelRequest_<ContainerAllocator> Type;

  nvpmodelRequest_()
    : nvpmodel()  {
    }
  nvpmodelRequest_(const ContainerAllocator& _alloc)
    : nvpmodel(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _nvpmodel_type;
  _nvpmodel_type nvpmodel;





  typedef boost::shared_ptr< ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct nvpmodelRequest_

typedef ::ros_jetson_stats::nvpmodelRequest_<std::allocator<void> > nvpmodelRequest;

typedef boost::shared_ptr< ::ros_jetson_stats::nvpmodelRequest > nvpmodelRequestPtr;
typedef boost::shared_ptr< ::ros_jetson_stats::nvpmodelRequest const> nvpmodelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator1> & lhs, const ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator2> & rhs)
{
  return lhs.nvpmodel == rhs.nvpmodel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator1> & lhs, const ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_jetson_stats

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fac0d4a363e336a74a2265c4c0f32e9";
  }

  static const char* value(const ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fac0d4a363e336aULL;
  static const uint64_t static_value2 = 0x74a2265c4c0f32e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_jetson_stats/nvpmodelRequest";
  }

  static const char* value(const ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# NV Power Model selection\n"
"\n"
"string nvpmodel\n"
;
  }

  static const char* value(const ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nvpmodel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nvpmodelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_jetson_stats::nvpmodelRequest_<ContainerAllocator>& v)
  {
    s << indent << "nvpmodel: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.nvpmodel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_JETSON_STATS_MESSAGE_NVPMODELREQUEST_H
