id: maixcam_project
name: 测试程序
version: 1.0.0
author: xt
icon: ''
desc: 主要用于测试uart通信
files:
  - maixcam_tests\00_uart.py
  - maixcam_tests\01_qrcode_test.py
  - maixcam_tests\02_color_blob_center_test.py
  - maixcam_tests\02_color_blob_test.py
  - maixcam_tests\03_line_tracking_test.py
  - maixcam_tests\04_vision_mode_test.py
  - maixcam_tests\05_color_ring_test.py
  - maixcam_tests\06_color_ring_multi_circle_test.py
  - maixcam_tests\main.py
  - maixcam_tests\maixcam_uart_vision.py
  - maixcam_tests\README.md
  - app.yaml
  - main.py
