// Generated by gencpp from file ros_jetson_stats/fan.msg
// DO NOT EDIT!


#ifndef ROS_JETSON_STATS_MESSAGE_FAN_H
#define ROS_JETSON_STATS_MESSAGE_FAN_H

#include <ros/service_traits.h>


#include <ros_jetson_stats/fanRequest.h>
#include <ros_jetson_stats/fanResponse.h>


namespace ros_jetson_stats
{

struct fan
{

typedef fanRequest Request;
typedef fanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct fan
} // namespace ros_jetson_stats


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_jetson_stats::fan > {
  static const char* value()
  {
    return "f745cc3cd10b95c8e8f7fabace50fbb1";
  }

  static const char* value(const ::ros_jetson_stats::fan&) { return value(); }
};

template<>
struct DataType< ::ros_jetson_stats::fan > {
  static const char* value()
  {
    return "ros_jetson_stats/fan";
  }

  static const char* value(const ::ros_jetson_stats::fan&) { return value(); }
};


// service_traits::MD5Sum< ::ros_jetson_stats::fanRequest> should match
// service_traits::MD5Sum< ::ros_jetson_stats::fan >
template<>
struct MD5Sum< ::ros_jetson_stats::fanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_jetson_stats::fan >::value();
  }
  static const char* value(const ::ros_jetson_stats::fanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_jetson_stats::fanRequest> should match
// service_traits::DataType< ::ros_jetson_stats::fan >
template<>
struct DataType< ::ros_jetson_stats::fanRequest>
{
  static const char* value()
  {
    return DataType< ::ros_jetson_stats::fan >::value();
  }
  static const char* value(const ::ros_jetson_stats::fanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_jetson_stats::fanResponse> should match
// service_traits::MD5Sum< ::ros_jetson_stats::fan >
template<>
struct MD5Sum< ::ros_jetson_stats::fanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_jetson_stats::fan >::value();
  }
  static const char* value(const ::ros_jetson_stats::fanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_jetson_stats::fanResponse> should match
// service_traits::DataType< ::ros_jetson_stats::fan >
template<>
struct DataType< ::ros_jetson_stats::fanResponse>
{
  static const char* value()
  {
    return DataType< ::ros_jetson_stats::fan >::value();
  }
  static const char* value(const ::ros_jetson_stats::fanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_JETSON_STATS_MESSAGE_FAN_H
