// Generated by gencpp from file ros_jetson_stats/jetson_clocksResponse.msg
// DO NOT EDIT!


#ifndef ROS_JETSON_STATS_MESSAGE_JETSON_CLOCKSRESPONSE_H
#define ROS_JETSON_STATS_MESSAGE_JETSON_CLOCKSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_jetson_stats
{
template <class ContainerAllocator>
struct jetson_clocksResponse_
{
  typedef jetson_clocksResponse_<ContainerAllocator> Type;

  jetson_clocksResponse_()
    : return(false)  {
    }
  jetson_clocksResponse_(const ContainerAllocator& _alloc)
    : return(false)  {
  (void)_alloc;
    }



   typedef uint8_t _return_type;
  _return_type return;





  typedef boost::shared_ptr< ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> const> ConstPtr;

}; // struct jetson_clocksResponse_

typedef ::ros_jetson_stats::jetson_clocksResponse_<std::allocator<void> > jetson_clocksResponse;

typedef boost::shared_ptr< ::ros_jetson_stats::jetson_clocksResponse > jetson_clocksResponsePtr;
typedef boost::shared_ptr< ::ros_jetson_stats::jetson_clocksResponse const> jetson_clocksResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator1> & lhs, const ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator2> & rhs)
{
  return lhs.return == rhs.return;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator1> & lhs, const ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_jetson_stats

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88eeb9c2a71b8e1ccaf759811ce45dd0";
  }

  static const char* value(const ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88eeb9c2a71b8e1cULL;
  static const uint64_t static_value2 = 0xcaf759811ce45dd0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_jetson_stats/jetson_clocksResponse";
  }

  static const char* value(const ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool return\n"
;
  }

  static const char* value(const ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.return);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jetson_clocksResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_jetson_stats::jetson_clocksResponse_<ContainerAllocator>& v)
  {
    s << indent << "return: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.return);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_JETSON_STATS_MESSAGE_JETSON_CLOCKSRESPONSE_H
