// Generated by gencpp from file ros_jetson_stats/jetson_clocksRequest.msg
// DO NOT EDIT!


#ifndef ROS_JETSON_STATS_MESSAGE_JETSON_CLOCKSREQUEST_H
#define ROS_JETSON_STATS_MESSAGE_JETSON_CLOCKSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_jetson_stats
{
template <class ContainerAllocator>
struct jetson_clocksRequest_
{
  typedef jetson_clocksRequest_<ContainerAllocator> Type;

  jetson_clocksRequest_()
    : status(false)  {
    }
  jetson_clocksRequest_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> const> ConstPtr;

}; // struct jetson_clocksRequest_

typedef ::ros_jetson_stats::jetson_clocksRequest_<std::allocator<void> > jetson_clocksRequest;

typedef boost::shared_ptr< ::ros_jetson_stats::jetson_clocksRequest > jetson_clocksRequestPtr;
typedef boost::shared_ptr< ::ros_jetson_stats::jetson_clocksRequest const> jetson_clocksRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator1> & lhs, const ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator1> & lhs, const ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_jetson_stats

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_jetson_stats/jetson_clocksRequest";
  }

  static const char* value(const ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# jetson_clocks selection\n"
"\n"
"bool status\n"
;
  }

  static const char* value(const ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jetson_clocksRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_jetson_stats::jetson_clocksRequest_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_JETSON_STATS_MESSAGE_JETSON_CLOCKSREQUEST_H
