# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from xrobot_msgs/ParamConfig.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ParamConfig(genpy.Message):
  _md5sum = "f701675f55a47d8728e25b639a888073"
  _type = "xrobot_msgs/ParamConfig"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """########################################
# CONSTANTS
########################################
# Chassis Type
uint8 DIFFERENTIAL_DRIVE  = 0
uint8 ACKERMANN  = 1
uint8 MECANUM  = 2

# Arm Type

########################################
# Messages
########################################
uint8 chassis_type      # 底盘类型
float32 x_speed_scale     # 遥控的速度比例
float32 y_speed_scale 
float32 w_speed_scale"""
  # Pseudo-constants
  DIFFERENTIAL_DRIVE = 0
  ACKERMANN = 1
  MECANUM = 2

  __slots__ = ['chassis_type','x_speed_scale','y_speed_scale','w_speed_scale']
  _slot_types = ['uint8','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       chassis_type,x_speed_scale,y_speed_scale,w_speed_scale

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ParamConfig, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.chassis_type is None:
        self.chassis_type = 0
      if self.x_speed_scale is None:
        self.x_speed_scale = 0.
      if self.y_speed_scale is None:
        self.y_speed_scale = 0.
      if self.w_speed_scale is None:
        self.w_speed_scale = 0.
    else:
      self.chassis_type = 0
      self.x_speed_scale = 0.
      self.y_speed_scale = 0.
      self.w_speed_scale = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B3f().pack(_x.chassis_type, _x.x_speed_scale, _x.y_speed_scale, _x.w_speed_scale))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.chassis_type, _x.x_speed_scale, _x.y_speed_scale, _x.w_speed_scale,) = _get_struct_B3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B3f().pack(_x.chassis_type, _x.x_speed_scale, _x.y_speed_scale, _x.w_speed_scale))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.chassis_type, _x.x_speed_scale, _x.y_speed_scale, _x.w_speed_scale,) = _get_struct_B3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B3f = None
def _get_struct_B3f():
    global _struct_B3f
    if _struct_B3f is None:
        _struct_B3f = struct.Struct("<B3f")
    return _struct_B3f
