// Generated by gencpp from file serial_comm/RobotControl.msg
// DO NOT EDIT!


#ifndef SERIAL_COMM_MESSAGE_ROBOTCONTROL_H
#define SERIAL_COMM_MESSAGE_ROBOTCONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_comm
{
template <class ContainerAllocator>
struct RobotControl_
{
  typedef RobotControl_<ContainerAllocator> Type;

  RobotControl_()
    : motor1_speed(0)
    , motor2_speed(0)
    , motor3_speed(0)
    , motor4_speed(0)
    , joint1_angle(0)
    , joint2_angle(0)
    , joint3_angle(0)
    , wrist_angle(0)
    , gripper_angle(0)
    , rest_flag(0)  {
    }
  RobotControl_(const ContainerAllocator& _alloc)
    : motor1_speed(0)
    , motor2_speed(0)
    , motor3_speed(0)
    , motor4_speed(0)
    , joint1_angle(0)
    , joint2_angle(0)
    , joint3_angle(0)
    , wrist_angle(0)
    , gripper_angle(0)
    , rest_flag(0)  {
  (void)_alloc;
    }



   typedef int16_t _motor1_speed_type;
  _motor1_speed_type motor1_speed;

   typedef int16_t _motor2_speed_type;
  _motor2_speed_type motor2_speed;

   typedef int16_t _motor3_speed_type;
  _motor3_speed_type motor3_speed;

   typedef int16_t _motor4_speed_type;
  _motor4_speed_type motor4_speed;

   typedef int16_t _joint1_angle_type;
  _joint1_angle_type joint1_angle;

   typedef int16_t _joint2_angle_type;
  _joint2_angle_type joint2_angle;

   typedef int16_t _joint3_angle_type;
  _joint3_angle_type joint3_angle;

   typedef int16_t _wrist_angle_type;
  _wrist_angle_type wrist_angle;

   typedef int16_t _gripper_angle_type;
  _gripper_angle_type gripper_angle;

   typedef uint8_t _rest_flag_type;
  _rest_flag_type rest_flag;





  typedef boost::shared_ptr< ::serial_comm::RobotControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_comm::RobotControl_<ContainerAllocator> const> ConstPtr;

}; // struct RobotControl_

typedef ::serial_comm::RobotControl_<std::allocator<void> > RobotControl;

typedef boost::shared_ptr< ::serial_comm::RobotControl > RobotControlPtr;
typedef boost::shared_ptr< ::serial_comm::RobotControl const> RobotControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_comm::RobotControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_comm::RobotControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_comm::RobotControl_<ContainerAllocator1> & lhs, const ::serial_comm::RobotControl_<ContainerAllocator2> & rhs)
{
  return lhs.motor1_speed == rhs.motor1_speed &&
    lhs.motor2_speed == rhs.motor2_speed &&
    lhs.motor3_speed == rhs.motor3_speed &&
    lhs.motor4_speed == rhs.motor4_speed &&
    lhs.joint1_angle == rhs.joint1_angle &&
    lhs.joint2_angle == rhs.joint2_angle &&
    lhs.joint3_angle == rhs.joint3_angle &&
    lhs.wrist_angle == rhs.wrist_angle &&
    lhs.gripper_angle == rhs.gripper_angle &&
    lhs.rest_flag == rhs.rest_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_comm::RobotControl_<ContainerAllocator1> & lhs, const ::serial_comm::RobotControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serial_comm::RobotControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_comm::RobotControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_comm::RobotControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_comm::RobotControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_comm::RobotControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_comm::RobotControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_comm::RobotControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c444a667b2720c4168deb47dd4f537a3";
  }

  static const char* value(const ::serial_comm::RobotControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc444a667b2720c41ULL;
  static const uint64_t static_value2 = 0x68deb47dd4f537a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_comm::RobotControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_comm/RobotControl";
  }

  static const char* value(const ::serial_comm::RobotControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_comm::RobotControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 motor1_speed\n"
"int16 motor2_speed\n"
"int16 motor3_speed\n"
"int16 motor4_speed\n"
"int16 joint1_angle\n"
"int16 joint2_angle\n"
"int16 joint3_angle\n"
"int16 wrist_angle\n"
"int16 gripper_angle\n"
"uint8 rest_flag\n"
;
  }

  static const char* value(const ::serial_comm::RobotControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_comm::RobotControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor1_speed);
      stream.next(m.motor2_speed);
      stream.next(m.motor3_speed);
      stream.next(m.motor4_speed);
      stream.next(m.joint1_angle);
      stream.next(m.joint2_angle);
      stream.next(m.joint3_angle);
      stream.next(m.wrist_angle);
      stream.next(m.gripper_angle);
      stream.next(m.rest_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_comm::RobotControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_comm::RobotControl_<ContainerAllocator>& v)
  {
    s << indent << "motor1_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor1_speed);
    s << indent << "motor2_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor2_speed);
    s << indent << "motor3_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor3_speed);
    s << indent << "motor4_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.motor4_speed);
    s << indent << "joint1_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.joint1_angle);
    s << indent << "joint2_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.joint2_angle);
    s << indent << "joint3_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.joint3_angle);
    s << indent << "wrist_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.wrist_angle);
    s << indent << "gripper_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gripper_angle);
    s << indent << "rest_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rest_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_COMM_MESSAGE_ROBOTCONTROL_H
